language: php

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps -a
  - docker exec -t $(docker ps -qf "name=app") bash -c "composer install -n"

script:
  - docker exec -t $(docker ps -qf "name=app") bash -c "./vendor/bin/phpunit"
