name: Syntax Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["7.1", "7.2", "7.3", "7.4", "8.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Syntax Checks
        run: docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php${{ matrix.php }} phplint examples src tests
